### ISSUE TITLE
Handle explicit infinity values for unbounded constraints

### ISSUE THREAD

**Issue by kvikshaug** [opencobra/optlang#191]
Using `math.inf` or `float('inf')` for bounds results in problems with de/serialization, varying somewhat depending on the chosen solver. Infinities should be handled as when the bound is not specified.

Here is a minimal reproducible example with glpk, which will successfully serialize but not deserialize:

```python
from optlang.glpk_interface import Model, Variable, Constraint, Objective
from swiglpk import *
import math
import pickle

x1 = Variable('x1', lb=0)
x2 = Variable('x2', lb=-math.inf)
c = Constraint(x1 + x2, ub=100)
model = Model()
model.add([c])

with open('pickle', 'wb') as f:
    pickle.dump(model, f)

with open('pickle', 'rb') as f:
    model = pickle.load(f)
```

Exception message:

```
Exception: The GLPK file /tmp/tmp75yn29e3.glpk does not seem to contain a valid GLPK problem:
```

Output from glpk:

```
p:4: error: column lower bound/fixed value missing or invalid
```

Generated GLPK problem file:

```
p lp min 1 2 2
i 1 u 100
n i 1 38ffbf5a-f244-11e8-a2ad-0242ac130002
j 1 d -inf 10
n j 1 x2
n j 2 x1
a 1 1 1
a 1 2 1
e o f
```

**Comment by KristianJensen** [comment]
Are there any situations where specifying an infinite bound instead of None would be necessary/preferable?
In my head an inequality like `x > -inf` is mathematically pointless, so I do not necessarily agree that infinities should be handled as when the bound is not specified.
Instead of introducing code to handle infinities in a consistent way, I would lean towards specifying in the documentation that bounds should be finite numbers or None.
