### ISSUE TITLE
docplex integration

### ISSUE THREAD

**Issue by Paulocracy** [opencobra/optlang#209]
Hello :D
I wanted to ask if you have plans to integrate the [docplex](https://pypi.org/project/docplex/) package as an alternative to the cplex package for optlang's CPLEX interface since docplex seems to be more actively maintained by IBM.
Kind regards :-)
P.S.B.

**Comment by cdiener** [comment]
I recently looked into this a bit more and docplex actually just wraps around the cplex python package and uses that under the hood. So this would probably just make everything a bit slower without allowing for more supported python versions. In terms of maintenance both seem to receive similar attention from IBM (mostly because one depends on the other). So I think it would not bring much advantage to add this here for now.

**Comment by assaron** [comment]
To record in case someone have the same problem. I wasn't able to install cplex package initially: only docplex package was provided with the CPLEX distribution (22.1) and `pip install cplex` couldn't find the package. Turns out I had python 3.12 and `cplex` was available for python <= 3.11. 

I'm not sure what's the CPLEX plans are, but it could be relevant to reopen this issue, as the old package could get deprecated completely.

**Comment by assaron** [comment]
Oops, I guess my bad, I was looking at the wrong place. Cplex python package is located at the directory like this: `CPLEX_Studio221/cplex/python/3.9/x86-64_linux`
