### ISSUE TITLE
optlang 1.4.6 breaks cobrapy

### ISSUE THREAD

**Issue by Midnighter** [opencobra/optlang#220]
The new optlang version breaks cobrapy in two places. It seems to be specific to GLPK (at least not seeing it with CPLEX).

1. There is an error with `Configuration.__setstate__` with the tolerances key. This happens when loading pickle files written with optlang before 1.4.6 and loading them with 1.4.6.

```
data_directory = '/home/moritz/Codebase/opencobra/cobrapy/src/cobra/test/data/'

    @pytest.fixture(scope="module")
    def mini_model(data_directory):
        """Fixture for mini model."""
        with open(join(data_directory, "mini.pickle"), "rb") as infile:
>           return load(infile)

src/cobra/test/test_io/conftest.py:17:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <optlang.glpk_interface.Configuration object at 0x7f7bfec52978>, state = {'presolve': 'auto', 'timeout': None, 'verbosity': 0}

    def __setstate__(self, state):
        self.__init__()
        for key, val in six.iteritems(state):
            if key != "tolerances":
                setattr(self, key, val)
>       for key, val in six.iteritems(state["tolerances"]):
E       KeyError: 'tolerances'

../../../.virtualenvs/cobra/lib/python3.6/site-packages/optlang/glpk_interface.py:408: KeyError
```

2. Setting unsupported optimality criteria now raises an `AttributeError`

```
model = <Model e_coli_core at 0x7f7be7506518>, opt_solver = 'optlang-glpk'

    def test_metabolite_summary_to_frame(model, opt_solver):
        """Test that the summary's method ``to_frame`` can be called."""
>       model.solver = opt_solver

src/cobra/test/test_summary/test_metabolite_summary.py:39:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src/cobra/util/context.py:111: in wrapper
    func(self, new_value)
src/cobra/core/model.py:168: in solver
    self._solver = interface.Model.clone(self._solver)
../../../.virtualenvs/cobra/lib/python3.6/site-packages/optlang/interface.py:1142: in clone
    new_model.configuration = interface.Configuration.clone(model.configuration, problem=new_model)
../../../.virtualenvs/cobra/lib/python3.6/site-packages/optlang/interface.py:1003: in clone
    return cls(problem=problem, **parameters)
../../../.virtualenvs/cobra/lib/python3.6/site-packages/optlang/glpk_interface.py:394: in __init__
    setattr(self.tolerances, key, val)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <optlang.util.SolverTolerances object at 0x7f7be74d4470>, key = 'optimality', value = 1e-06

    def __setattr__(self, key, value):
        if key not in self._functions:
>           raise AttributeError(key + " is not an available tolerance parameter with this solver")
E           AttributeError: optimality is not an available tolerance parameter with this solver

../../../.virtualenvs/cobra/lib/python3.6/site-packages/optlang/util.py:286: AttributeError
```

I would suggest that in future we make pre-releases and ensure that at least cobrapy, cameo, and memote test suites pass with the pre-release.

**Comment by KristianJensen** [comment]
Hmm, that's unfortunate. No. 1 was also mentioned in #214, but I wouldn't call it a bug as such. From the optlang side, pickling was never meant as a long-term way to store models, and compatibility across versions has been coincidental. Is that a feature that is required for cobrapy? For now it should be easily fixable by changing the offending line to
`for key, val in six.iteritems(state.get("tolerances", {)):`

For 2., I think the issue is that the tolerance configuration interface was initially added as a somewhat experimental feature, and the intended behaviour was never rigorously defined, and thus not tested. Mainly due to the fact that it differs so much between solvers, it was mainly meant as a convenience interface to the underlying solver configurations. I think raising an AttributeError (or another error) when trying to set an unsupported tolerance sounds like reasonable behaviour, but we should probably define in more detail what the optlang tolerance interface should and should not be able to do.

I agree that we should make sure that optlang releases do not break cobrapy. Instead of making pre-releases, could we maybe simply set up the optlang github workflow to run the cobrapy tests on PR's to master, and require them to pass before merging?

**Comment by cdiener** [comment]
Yeah that would be expected. This was a bug in optlang where it did not pickle the configuration which was fixed at some point. If you regenerate the pickles it should work. I fear pickled models are unlikely to work across different cobrapy and optlang versions.

**Comment by Midnighter** [comment]
1. Can be easily fixed and I agree, it is not a feature that we need to support. I merely reported it for completeness sake.
2. Is a consequence of setting a solver interface and not of loading a file (although I guess it leverages pickle to clone the model). I was surprised that it showed up only now. We will either need to make changes here or catch the error in cobrapy.

> I agree that we should make sure that optlang releases do not break cobrapy. Instead of making pre-releases, could we maybe simply set up the optlang github workflow to run the cobrapy tests on PR's to master, and require them to pass before merging?

Yes, this is certainly possible. Although we are still in trouble because we can't test proprietary solvers. It is somehow possible to set up a local GitHub runner. Would be awesome to get a local box at some university/institute that has CPLEX and Gurobi to run tests for us.

**Comment by cdiener** [comment]
I agree that it would be much easier if all solvers in optlang would support the same configuration but I would not know how to handle things not supported by the core solver. I ran into similar issue with OSQP since every other solver has a simplex method and OSQP does not. Maybe just set the ones that don't raise error and leave the rest as default? Either way it seems more an optlang issue since it basically is the behavior of optlang.Model.clone that is the issue here.

**Comment by KristianJensen** [comment]
Yes, I had missed that it was caused by internal optlang functions. I agree that just skipping any incompatible tolerance settings is the best way to solve it.

**Comment by Midnighter** [comment]
I guess this can be closed but let's release 1.4.7 as soon as possible.

**Comment by jgilis** [comment]
Hi everyone,

I am going through the docs of https://github.com/opencobra/Medusa.
These docs use a pickled model generated with optlang 1.4.3 (https://github.com/opencobra/Medusa/blob/development/medusa/test/data/Staphylococcus_aureus_ensemble.pickle), which I now try to load with optlang 1.8.2 (GLPK).

As described by @Midnighter, this throws the error (1) with `Configuration.__setstate__`.

Do you have any suggestions of how I could rescue this in the cleanest possible way? I wouldn't mind e.g. loading it with optlang <1.4.6 and repickling.

Best,

Jeroen

**Comment by cdiener** [comment]
Hi Jeroen,

Yeah that is a bit complicated because newer optlang versions don't support pickle objects that old. For cobrapy it was somewhat easier because the pickles there are built from other formats (SBML) so we just had to load the model from there and resave the pickle. 

In your case there would be two options:

1. Manually fix the state dict. For that you would load the model with the old optlang version, call `__getstate__()` on it and save the resulting dict instead of the pickled object. After that unpickle this into an env with the new optlang version and adjust the tolerances part of the dict so you can pass it to `__setstate__()` of an empty model.
2. Hack the `__setstate__()` method in the current optlang. You could add an if statement before accessing the "tolerances" entry. Just skipping it should be fine. I would simply use the default tolerances in that case. There is a chance that will throw additional errors if other parts of the object serialization have changed as well. If that works, we might want to add it to the current code base to improve backwards compatibility. 

I would probably go for option 2.

**Comment by jgilis** [comment]
Hi @cdiener,

Thank you for the suggestions! I can confirm that option 2, i.e., adding a simple if statement in `glpk_interface.py` like:

```
 if "tolerances" in state:            
    for key, val in state["tolerances"].items():
        if key in self._tolerance_functions():
            setattr(self.tolerances, key, val)
```

rescues the medusa tutorial code, without needing any additional changes (as far as I can see). 

Not sure if it is safe to add this hack to the current code base, but for me it worked.

Best,

Jeroen
