### ISSUE TITLE
Scaling output

### ISSUE THREAD

**Issue by mauliadianti** [opencobra/optlang#238]
### Question

dear all, I have run my optlang perfectly, and now I want to not display this scaling output
![Capture](https://user-images.githubusercontent.com/70008045/133763319-8895dd78-78f6-48ff-bac1-ae1f68190e98.PNG)
I found some articles here https://en.wikibooks.org/wiki/GLPK/Terminal_output they say that the scaling output can disable with "--noscale command-line option" where or how can I do that? 

thanks before.

**Comment by Midnighter** [comment]
You can actually control this by configuring optlang's [verbosity](https://optlang.readthedocs.io/en/latest/Configuration.html#optlang.interface.Configuration.verbosity).

I think there is some bug with the GLPK interface which (for now) requires that you set the verbosity to 0 before you create a model, otherwise you see above message.

**Comment by mauliadianti** [comment]
hai @Midnighter thanks for the answer, but unfortunately I can't solve the issue using your suggestion, Turns out I just split the output and just choose what I wanted to get, that was the best I can do I think, It's been a long time since I am not open my email, so sorry for a late response from me, but thanks anyway for the answer,
