### ISSUE TITLE
Sets

### ISSUE THREAD

**Issue by sjpfenninger** [opencobra/optlang#60]
Are there any plans to implement sets over which parameters, variables and constraints can be defined? E.g. as implemented in [Pyomo](https://software.sandia.gov/downloads/pub/coopr/CooprGettingStarted.html#_sets) or [GAMS](https://www.gams.com/latest/docs/userguides/userguide/_u_g__set_definition.html).

I think this would be nice - but likely quite a substantial change to the codebase?

**Comment by KristianJensen** [comment]
For continuous variables you can specify the domain using the bounds. For discrete variables you can only constrain the value to take on integer values (and bound them of course). Assigning arbitrary sets as variable domains, e.g. `x.domain = {2, 5, 13}` (is this what you meant?) is not possible directly, but can be achieved through a few auxiliary variables.

**Comment by KristianJensen** [comment]
Since none of the solvers support the use of domain sets, adding it will be somewhat complicated. One thing we might do is to simplify the construction of conditional constraints by implementing the indicator variable interface* in solvers that don't support this natively, e.g. through the Big M method.

* This way it would be possible to do `const = Constraint(var1 + 2*var2, lb=0, indicator_variable=y_var, active_when=1)`, which results in a constraint that's only active when `y_var` has a value of 1. Currently only cplex supports this.

**Comment by sjpfenninger** [comment]
Actually I was referring to sets as used in high-level mathematical programming languages -- see e.g. https://www.gams.com/latest/docs/userguides/userguide/_u_g__set_definition.html -- which is a little bit different, but in fact not required here since Python already provides the necessary features.

On revisiting this now, it's clear that you use dicts in the [example](https://optlang.readthedocs.io/en/latest/#example) in your docs to achieve this - I guess that is the sensible way to go, so perhaps this issue should be closed.

(your interpretation of my request sounds like a useful feature too though)
